sudo: false
language: node_js
branch:
  - master
node_js:
  - '8'
cache: 
  directories:
    - node_modules
before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm update
  - npm run lint
  - npm run test:ci
